nome: "Vitor"
idade: 24

objeto: 
 versao: 2
 arquivo: "teste.txt"

versao: 2
versao_completa: 3.14 

nulo: ~
nulo_dois: null

verdadeiro: True
verdadeiro_dois: On

false: false
falso_dois: Off

lista: [1, 2, 3, 4, 5]

lista_dois:
 - "teste"
 - 10
 - outro teste
 - True
obj: {a: 1, b: 2, c: 3}

objeto:
  a: 1
  b: 2
  objeto_interno:
    x: 2