apiVersion: apps/v1 ###Define qual api do kubernets será usada
kind: Deployment ###Diz qual recurso estamos usando
metadata: 
  name: vitorpioflaskkubprojeto ###identificação no cluster
spec:
  replicas: 4 ###diz que queremos 4 réplicas(pods) da aplicação Flask rodando
  selector: ###diz como o Deployment encontra os Pods que ele gerencia
    matchLabels:
      app: flask-app 
  template: ###esse é o modelo do Pod que será criado, com os rotulos de flask-app
    metadata:
      labels:
        app: flask-app
    spec: ###conteúdo do pod
      containers:  ### define os containers dentro do Pod
        - name: flask ### nome do container
          image: vitorpiovieira/vitorpioflaskkubprojeto:5 ### usa a essa imagem
        